backend:
  replicaCount: 1
  image:
    repository: omerteomim/backend
    tag: staging
    pullPolicy: IfNotPresent
  service:
    port: 5000
  resources:
    limits:
      cpu: "500m"
      memory: "256Mi"
    requests:
      cpu: "250m"
      memory: "128Mi"
frontend:
  replicaCount: 1
  image:
    repository: omerteomim/frontend
    tag: staging
    pullPolicy: IfNotPresent
  service:
    port: 80
  resources:
    limits:
      cpu: "500m"
      memory: "256Mi"
    requests:
      cpu: "250m"
      memory: "128Mi"
ingress:
  host: staging.teomim.site

namespace:
  name: psychometry-app-staging

externalsecrets:
  - secretkey: GROQ_API_KEY
    remoteRef:
      key: prod/psychometry-app/groq_api_key
      property: GROQ_API_KEY
  - secretkey: SUPABASE_URL
    remoteRef:
      key: prod/psychometry-app/supabase_url
      property: SUPABASE_URL
  - secretkey: SUPABASE_KEY
    remoteRef:
      key: prod/psychometry-app/supabase_key
      property: SUPABASE_KEY
  - secretkey: SUPABASE_SERVICE_ROLE_KEY
    remoteRef:
      key: prod/psychometry-app/supabase_service_role_key
      property: SUPABASE_SERVICE_ROLE_KEY
  - secretkey: SECRET_KEY
    remoteRef:
      key: prod/psychometry-app/secret_key
      property: SECRET_KEY