apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: psychometry-prod-app
  namespace: argocd
spec:
  destination:
    namespace: psychometry-app
    server: https://kubernetes.default.svc
  source:
    repoURL: 'https://github.com/omerteomim/bootcamp-project.git'
    targetRevision: HEAD
    path: chart-psychometric
    helm:
      valueFiles:
        - https://github.com/omerteomim/bootcamp-gitops.git/environments/prod/values.yml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true