backend:
  replicaCount: 1
  image:
    repository: omerteomim/backend
    tag: latest
    pullPolicy: IfNotPresent
  service:
    port: 5000
  resources:
    limits:
      cpu: "500m"
      memory: "256Mi"
    requests:
      cpu: "250m"
      memory: "128Mi"
frontend:
  replicaCount: 1
  image:
    repository: omerteomim/frontend
    tag: latest
    pullPolicy: IfNotPresent
  service:
    port: 80
  resources:
    limits:
      cpu: "500m"
      memory: "256Mi"
    requests:
      cpu: "250m"
      memory: "128Mi"
ingress:
  host: prod.teomim.site

namespace:
  name: psychometry-app-prod
  
externalSecrets:
  data:
    - secretkey: GROQ_API_KEY
      remoteRef:
        key: prod/psychometry-app/groq_api_key
    - secretkey: SUPABASE_URL
      remoteRef:
        key: prod/psychometry-app/supabase_url
    - secretkey: SUPABASE_KEY
      remoteRef:
        key: prod/psychometry-app/supabase_key
    - secretkey: SUPABASE_SERVICE_ROLE_KEY
      remoteRef:
        key: prod/psychometry-app/supabase_service_role_key
    - secretkey: SECRET_KEY
      remoteRef:
        key: prod/psychometry-app/secret_key